# Generated by Django 4.2.3 on 2025-03-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_employee_vacation_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('promotion', 'Promotion'), ('role_change', 'Role Change'), ('salary_change', 'Salary Change')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.employee')),
            ],
        ),
    ]
